### ISSUE TITLE
Tilda Tools does not work on Windows

### ISSUE THREAD

**Issue by Molive-0** [emfcamp/Mk4-Apps#87]
When trying to run various commands (such as sync) this error appears:

`C:\Users\moliv\Documents\Mk4-Apps-master\.development>.\tilda_tools.py sync
Traceback (most recent call last):
  File "C:\Users\moliv\Documents\Mk4-Apps-master\.development\tilda_tools.py", line 153, in <module>
    main()
  File "C:\Users\moliv\Documents\Mk4-Apps-master\.development\tilda_tools.py", line 97, in main
    add_metadata(path, resources)
  File "C:\Users\moliv\Documents\Mk4-Apps-master\.development\resources.py", line 145, in add_metadata
    resource.update(_normalize_metadata(read_metadata(stream)))
  File "C:\Users\moliv\Documents\Mk4-Apps-master\.development\metadata_reader.py", line 25, in read_metadata
    result["doc"] = _read_docstring(s)
  File "C:\Users\moliv\Documents\Mk4-Apps-master\.development\metadata_reader.py", line 37, in _read_docstring
    delimiter = _read_non_whitespace(s, 3)
  File "C:\Users\moliv\Documents\Mk4-Apps-master\.development\metadata_reader.py", line 131, in _read_non_whitespace
    result = s.read(1)
  File "C:\Users\moliv\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 448: character maps to <undefined>`

**Comment by Jake-E** [comment]
#58 should have fixed this. Is your repo behind?
