### ISSUE TITLE
Write timeout if try to use tilda_tools

### ISSUE THREAD

**Issue by bboortz** [emfcamp/Mk4-Apps#95]
If I try to use the tilda tools with the badge I always receive a "Receiving SerialTimeoutException: Write timeout".

The log output looks like this. I have also tried to specify the device
```
~/projects/Mk4-Apps$ sudo ./tilda_tools sync hello_world/
Local Test: PASS
Connected to badge: DONE
Stopping running app: DONE
WARN: No resources to copy found for pattern ['hello_world/']
Init copy via repl: Traceback (most recent call last):
  File "./tilda_tools", line 151, in <module>
    main()
  File "./tilda_tools", line 126, in main
    synced_resources = sync.sync(args, paths, resources, args.verbose, args.skip_wifi)
  File "/home/bb/projects/Mk4-Apps/.development/sync.py", line 34, in sync
    pyboard_util.init_copy_via_repl(args)
  File "/home/bb/projects/Mk4-Apps/.development/pyboard_util.py", line 167, in init_copy_via_repl
    pyb.enter_raw_repl()
  File "/home/bb/projects/Mk4-Apps/.development/pyboard.py", line 286, in enter_raw_repl
    self.serial.write(b'\r\x03\x03') # ctrl-C twice: interrupt any running program
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 552, in write
    raise writeTimeoutError
serial.serialutil.SerialTimeoutException: Write timeout
```

I am using Linux Mint 18
```
$ uname -a
Linux bb-ThinkPad-T500 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

lsusb output
```
us 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 060: ID 1cbe:0007 Luminary Micro Inc. 
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 002: ID 1050:0407 Yubico.com 
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```

**Comment by bboortz** [comment]
Fixed.

Just follow this instructions:

1.  connect your badge via USB to your computer
2.  start minicom `minicom -D /dev/ttyACM0 -b 115200`
3.  press several times ctrl-c and a the same time shorty reset.  You will see some response from the badge via serial
4.  quit minicom using ctrl-a q
5.  use tilda_tools
